### ISSUE TITLE
Find the printed format

### ISSUE THREAD

**Issue by XavierBoubert** [CodeCorico/MemoryOverflow#52]
As a gamer I want to print my cards easily so that I can play lol.

**Technical criteria:**
- [x] Add a black border for each card
- [x] Find a format to print the cards with a local printer.
  - [x] Add a print page
  - [x] Add "reversed" back cards for the print
  - [x] Add an explaination to print and create the cards

**Comment by MemoryOverflowAgent** [comment]
:+1: Thanks for your contribution **Agent XavierBoubert!**

However, The Machine has very specific contribution rules. Please update your contribution by following these goals:
- [ ] Your issue should be in [User Story](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-user-story-for-a-new-feature) or [Bug](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-how-to-reproduce-for-a-bug) format.

When you have updated your work, add a comment below to inform me.

**Comment by XavierBoubert** [comment]
Good now?

**Comment by MemoryOverflowAgent** [comment]
:+1: Thanks for your contribution **Agent XavierBoubert!**

However, The Machine has very specific contribution rules. Please update your contribution by following these goals:
- [ ] Your issue should be in [User Story](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-user-story-for-a-new-feature) or [Bug](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-how-to-reproduce-for-a-bug) format.

When you have updated your work, add a comment below to inform me.

**Comment by MemoryOverflowAgent** [comment]
:+1: Thanks for your contribution **Agent XavierBoubert!**

However, The Machine has very specific contribution rules. Please update your contribution by following these goals:
- [ ] Your issue should be in [User Story](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-user-story-for-a-new-feature) or [Bug](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-how-to-reproduce-for-a-bug) format.

When you have updated your work, add a comment below to inform me.

**Comment by MemoryOverflowAgent** [comment]
:+1: Thanks for your contribution **Agent XavierBoubert!**

However, The Machine has very specific contribution rules. Please update your contribution by following these goals:
- [ ] Your issue should be in [User Story](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-user-story-for-a-new-feature) or [Bug](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-how-to-reproduce-for-a-bug) format.

When you have updated your work, add a comment below to inform me.

**Comment by XavierBoubert** [comment]
Good now?

**Comment by MemoryOverflowAgent** [comment]
:+1: Thanks for your contribution **Agent XavierBoubert!**

However, The Machine has very specific contribution rules. Please update your contribution by following these goals:
- [ ] Your issue should be in [User Story](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-user-story-for-a-new-feature) or [Bug](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-how-to-reproduce-for-a-bug) format.

When you have updated your work, add a comment below to inform me.

**Comment by XavierBoubert** [comment]
Ok?
