### ISSUE TITLE
Fix locales

### ISSUE THREAD

**Issue by mebibou** [CodeCorico/MemoryOverflow#54]
**Bug**

`en_EN` is not a valid locale, it should be `en_US` or `en_GB` for example

**How to reproduce**

Look [here](https://github.com/CodeCorico/MemoryOverflow-website/tree/gh-pages/cards/fototse) for example

**Comment by MemoryOverflowAgent** [comment]
:+1: Thanks for your contribution **Agent mebibou!**

However, The Machine has very specific contribution rules. Please update your contribution by following these goals:
- [ ] Your issue should be in [User Story](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-user-story-for-a-new-feature) or [Bug](https://github.com/CodeCorico/MemoryOverflow/blob/master/CONTRIBUTING.md#write-a-how-to-reproduce-for-a-bug) format.

When you have updated your work, add a comment below to inform me.

**Comment by mebibou** [comment]
Done
